# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ])
  (
    if stdenv.isAarch64 then
      {
        pname = "brave";
        version = "1.67.119";
        url = "https://github.com/brave/brave-browser/releases/download/v1.67.119/brave-browser_1.67.119_arm64.deb";
        hash = "sha256-j0SDqCKyCnS8lAAFya2ueOtWLhfxOJ3VM8b6qBS30h8=";
        platform = "aarch64-linux";
      }
    else if stdenv.isx86_64 then
      {
        pname = "brave";
        version = "1.67.119";
        url = "https://github.com/brave/brave-browser/releases/download/v1.67.119/brave-browser_1.67.119_amd64.deb";
        hash = "sha256-6+HIztCwJ2zcvO1pEgHE+WeM6MFf3Ll7xnGtoGhnd3s=";
        platform = "x86_64-linux";
      }
    else
      throw "Unsupported platform."
  )
