# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ])
  (
    if stdenv.hostPlatform.isAarch64 then
      rec {
        pname = "brave";
        version = "1.70.126";
        url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-browser_${version}_arm64.deb";
        hash = "sha256-BADZS5lqCHJvKWaT6p5vGZfUIwhckmSmau9/0V4763U=";
        platform = "aarch64-linux";
      }
    else if stdenv.hostPlatform.isx86_64 then
      rec {
        pname = "brave";
        version = "1.70.126";
        url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-browser_${version}_amd64.deb";
        hash = "sha256-eNinbCwgzDGw8WwUjD/LY0ISsGM68N8QdZ2mDpcWcIk=";
        platform = "x86_64-linux";
      }
    else
      throw "Unsupported platform."
  )
